using System;
using System.Collections.Generic;
using System.Text;

namespace BackgroundLib
{
    public class ClassBackground
    {
        public string Name;
        public string Description;

        public ClassBackground() { }

        public ClassBackground(string name, string description)
        {
            Name = name;
            Description = description;
        }

        public List<ClassBackground> AlchemistBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Accidental Discovery", "Your keen intellect has always been an asset in your studies of the alchemical arts, but along with your logic and rationale, you have a “sense” for alchemy.This intuition sometimes leads to discoveries through methods most of your peers would never have thought possible, but that you somehow know will work."),
                new ClassBackground("Firebug", "Although you’ve studied all aspects of the alchemist’s craft, your have a talent for fire. Fire has always been a seductive and powerful force that you have either embraced with glee or focused care.You are adept at exploiting a weakness to fire when you recognize it."),
                new ClassBackground("Wasn't Strong Enough", "You suffered something at an early age that made you feel powerless. Maybe a relative died from plague, a friend was crushed beneath rubble you were too weak to move, or some other horrible tragedy occurred. You turned to alchemy to transcend the limitations of your physical form. Your relentless dedication has made your bolstering abilities more persistent."),
                new ClassBackground("Magic for the Uninclined", "You were always interested in the arcane, but lacked the innate magic of sorcerers or the single-minded dedication possessed by wizards. As a disciple of science, the magic of faith was also closed to you. You dedicated yourself to alchemy, focusing on extracts that mimic the magic you once hoped to wield. That original interest in magic still grants you occasional rare insight into the workings of your formulae."),
                new ClassBackground("Master Craftsman", "The first time you saw air mix with the shapeless goo of a tanglefoot bag or shielded your eyes at the heatless light of a sunrod, you became ensnared by the wonders of alchemy. You’ve since labored to learn the secrets to crafting such items."),
                new ClassBackground("Physician", "Alchemy was the natural outgrowth of your time spent learning the healer’s craft. Your first extracts were the accidental byproduct of making poultices and elixirs. Continuing your studies, you found the natural compassion you had as a healer mixing with an alchemist’s cold logic, forging you into a clinician unlike most others."),
                new ClassBackground("Formulae Stickler", "To you, alchemy is a delicate and complex symphony requiring multiple different elements to work together to produce the perfect result. Though others in your craft come up with ways to substitute certain ingredients when  aking bombs or mutagens, you disdain such practices, deeming them pollutions. To you, there is always a perfect ingredient and its addition makes your alchemy more potent."),
                new ClassBackground("Nature's Foe", "You lost something or someone important to you through the cruel indifference of nature. Perhaps you watched someone get swallowed by a storm-tossed sea or witnessed a summer forest fire destroy your home and all of your possessions. No matter the impetus, the unpredictability of nature made you feel small and helpless. Your subsequent devotion to alchemy has been in no small part due to a desire to exert control over nature itself, a domineering intent palpable to all creatures of nature."),
                new ClassBackground("To Recreate a Miracle", "Your life or the life of someone you loved was saved by a magical elixir. Witnessing this instilled a sense of awe for the art of alchemy.Although your research has not yet been able to recreate the sheer potency of that draught long ago, your years questing to duplicate it have made you adept at brewing potions."),
                new ClassBackground("Mad Alchemist", "Rampant curiosity and a near fearlessness of the unknown drove you to experiment with the rudiments of alchemy. That curiosity has uncovered interesting alchemical secrets, at the cost of alchemical instability. Some consider your experiments mad."),
            };
        }

        public List<ClassBackground> BarbarianBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Vengeance", "When you were young, a great wrong was done to you, a loved one, your family, or your people. This experience tore you apart and reduced you to a being of primal emotions. Dreams of vengeance became your only promise of comfort."),
                new ClassBackground("Champion of a God", "At your coming-of-age ritual, your deity, totem, or patron spirit sparked your soul with a religious zeal. This entity might be a beast spirit, a warmongering god, a demon lord, or some other supernatural entity. In the name of this otherworldly force you become an unstoppable warrior — the bane of all your tribe’s foes."),
                new ClassBackground("Conquest", "Upon coming of age, you went on your first raid, where you learned the thrill of violence and chaos and the satisfaction that came with the spoils of your victory. When your enemies dare to stand against you, your rage rekindles until you have conquered and subdued them."),
                new ClassBackground("Hated Foe", "In your formative years, you learned to despise a certain individual, tribe, kingdom, empire, race, or monster due to some slight it inflicted upon you or your people. This foe lurks ever close to your thoughts. So intense is your hatred that the mere thought of this foe can incite your rage."),
                new ClassBackground("Personal Flaw", "There is a part of yourself that you hate more than anything else.In your adolescence, you first realized this imperfection — to your lasting shame. This might be a gentle part of yourself you wish to eliminate or a brutal, prideful, greedy, or monstrous side you can’t control.Your rage is fueled by self - loathing, or  by projecting this part of yourself onto a foe you  wish to destroy."),
                new ClassBackground("Hatred of Civilization", "When you first encountered civilization in your youth, its weak and decadent people revolted you. Once, such people were free and strong, but rules and laws made them feeble. Your rage is the wild part — the pure part — of yourself that separates you from the craven ways of “civilized” people."),
                new ClassBackground("Persecution", "You grew up under the persecution of another power—perhaps a rival tribe, an expansionistic empire, or a tribe of violent monsters. Beaten and bloodied, your people barely survived the onslaught. But the beatings made you strong and taught you how to channel the pain into something useful. Since that time, the flame of rage has burned inside you, waiting to be released against your oppressors."),
                new ClassBackground("One of a Dying Breed", "You grew up knowing that your people were slowly dying out — that your extinction was inevitable in the face of the changing world. In youthful vigor, you declared that your fire would not be snuffed without a fight. Your rage stems from the desperate desire to be remembered, to make a mark upon the world before the sun sets on your dwindling kind. When you rage, a single thought permeates your burning mind: If you’re going down, you’re taking everyone with you."),
                new ClassBackground("Chaos Embraced", "You grew up in wild lands where there were no laws except for those of nature — the laws of the predator and the prey.You searched for meaning in the world, in the gods, in the prayers of priests, in the patterns of the stars, but you found nothing.There is no true order to the natural universe except for that of raw and unbridled power.Chaos is the natural state of all things, and that’s how you like it."),
                new ClassBackground("Bloodthirsty", "The first time you spilled a deserving foe’s blood and watched the thing’s life ebb out onto the hard ground, you found yourself filled with a mad, euphoric ecstasy like none other. The memory of this visceral experience returns to you in every battle, like an insatiable addiction that can only be abated with further bloodshed."),
            };
        }

        public List<ClassBackground> BardBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Celebrity", "In your formative years, you saw a player or troupe of players perform before an enthralled audience. That’s when you decided that you wanted to be up on that stage performing for the adulation of the crowd."),
                new ClassBackground("Cultural Mandate", "There has always been a revered storyteller in your culture. This could be an official skald, a royal minstrel, the washerman who spins parables and folk wisdom, or the old farmer who tells tall tales at the pub. Ever since you were young, your community has groomed you to fulfill this role."),
                new ClassBackground("Dabbler", "Whether you grew up rich or poor, you refused to accept the limits imposed by your social class or means.In your youth, you determined to learn a little bit of all there was to know. You may not be the master of any one career, but the breadth of your experience is wide, textured, and diverse."),
                new ClassBackground("For Love", "When you were young, you tried to express yourself to your beloved using song or poetry.Driven by desire, you refined your skill and learned to articulate raw emotion in story and song."),
                new ClassBackground("Gift", "Someone gave you a special instrument or a collection of songs and stories at a time in your life when you needed them most. You have treasured this object above all other possessions, and it started you on a path to new songs and stories."),
                new ClassBackground("Ongoing Patron", "When you were young, a person with money or power took an interest in your art and sponsored you. Most of what you created was dictated by the patron’s tastes, and you probably still work for this patron, who maintains a strong influence over your life."),
                new ClassBackground("Spy", "Someone once asked you to employ your artistic talents as an excuse to observe a person, steal an object, or retrieve a piece of information. Infiltrating various houses and estates in the guise of an actor, minstrel, or storyteller, you honed your art while being paid better than most other performers."),
                new ClassBackground("Troupe of Players", "You were born into, helped found, or fell in with a troupe of traveling players. You spent your early years rambling from one place to another — from tavern to tavern, town to town, or even between countries. Long hours traveling gave you plenty of time to practice and hone your skill."),
                new ClassBackground("Virtuoso", "One day, you picked up an instrument or told a tale, and your raw natural ability captivated everyone who saw you perform. Words and music have always come to you effortlessly, as naturally as breathing."),
                new ClassBackground("Worldshaker", "Since childhood, you’ve observed the world around you and translated those observations into story and song. Your unique, unabashed vision resonated with the audience, revealing new perspectives as well as simple truths. You’re used to people quoting your words and looking up to you, though some authority figures deem you a rabble-rouser and troublemaker."),
            };
        }

        public List<ClassBackground> CavalierBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Tragedy and Loss", "In your formative years, you experienced a significant tragedy that forged you into the person you’ve become."),
                new ClassBackground("Faith", "You embraced a religious faith at an early age and devoted your life to its ideals. You soon learned that it was not enough to follow and worship. Faiths need champions—people capable of defending the virtues, tenets, and precepts of the faith from those who would seek to corrupt, alter, or destroy it."),
                new ClassBackground("Champion of the People", "You grew up among common people. You were close to these people and you witnessed their oppression, their suffering, and their helplessness. Someone needed to stand up and protect them, and that someone would be you."),
                new ClassBackground("Squired", "You were a young squire who served a very different kind of knight. This knight taught you more than the art of battle: she taught you to live by a strict code to guide your actions and your sword."),
                new ClassBackground("Military Order", "At the beginning of your career, you served with a company of mercenaries, rogues, and professional soldiers. The experience taught you how to work strategically with diverse groups."),
                new ClassBackground("Personal Code", "In your early years, you made sense of the chaotic, disorderly world you grew up in by formulating your own code of ethics and behavior. Though you are the ultimate arbiter and authority over this code, you do not break it, for without it your existence loses all meaning."),
                new ClassBackground("Equestrian", "The first time you rode a horse, you discovered a kinship with it and knew you were born to ride, and the superior horsemanship you gained through your bond with the animal propelled you into the ranks of the cavaliers."),
                new ClassBackground("Entitlement", "You became a cavalier early in your career, not by personal action or effort but by family favor, connections, or promotion. You were given fine weapons, tactical training, a mount, and the edicts of your order. Now you must learn how to follow them."),
                new ClassBackground("Honor Bound", "Long ago, a promise was made that you are bound to fulfill. This could be a vow you made in your youth, or one made by an ancient forebear. Regardless, you must follow a cavalier’s code despite any personal doubts or misgivings until you have fulfilled the terms of the oath."),
                new ClassBackground("Old Soldier", "When you were young, you discovered an ancient chivalric oath sworn by knights of yore. Though the beautiful edicts of this oath seem to have been forgotten by the world, this old way fulfills you and gives you purpose."),
            };
        }

        public List<ClassBackground> ClericBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Angelic Encounter", "A supernatural being, such as an angel or demon, appeared to you and proclaimed that you were destined to perform a great task in service to your god. You might have tried to deny it—and you even might still have doubts — but eventually you took up the mantle of a holy warrior and chose to meet this destiny head on, either to prove to yourself that you’re worthy of such a destiny or to show your supernatural messenger that you cannot be pigeon-holed so easily."),
                new ClassBackground("Atonement", "In your youth, you committed actions you are not proud of. Your deeds left dark stains upon your soul, ones so deep they might take a lifetime to wash away. When you hit rock-bottom — whether through greed, addiction, hedonism, or simply lack of good sense — you turned to faith, vowing to atone for all of the horrible acts you’ve committed."),
                new ClassBackground("Converted", "In your early life, you followed a different faith, a different god or powerful entity, or perhaps no faith at all. A representative of your current faith showed you the error of your ways and converted you, and you couldn’t be happier. You can only hope to do for others what this individual did for you."),
                new ClassBackground("Devoted", "From your earliest memory, you’ve had a close relationship with your deity. This entity has been a constant presence in your life: your greatest comfort, best companion, truest love, or some combination of the three. You’ve never had to see or speak with your deity to know that he watches over you, and the beliefs and criticisms of others do not faze you—your faith is enough."),
                new ClassBackground("Healed", "As a child, you were afflicted with a terrible physical or mental illness or a debilitating wound that prevented you from functioning in society. A miracle worker touched your body and commanded you to be well, and—for perhaps the first time in your life — you were whole.Now you live your life in tribute to the deity whose divine healer restored you, and perhaps hope to bestow similar gifts unto deserving nonbelievers."),
                new ClassBackground("Reborn", "You died or nearly died. In the midst of this experience, your mind came to a place of quiet where you witnessed your deity or its agents pulling your body and spirit back from the brink of death. Every day since has been a gift, and you strive to understand the reason you have been saved while countless others perish."),
                new ClassBackground("Religious Colony", "You grew up in a religious colony or settlement. This may have been a small village in the hinterlands or a kingdomsized theocracy devoted to a single religion. When you came of age, you decided to serve your god and country as a cleric, a choice that garnered respect, dignity, and honor among your people."),
                new ClassBackground("Revelation", "In your youth, a deity granted you visions or dreams that revealed startling truths. These visions might have been prophetic, deeply insightful, or filled with extraordinary solutions to problems that plagued you, your family, or your community. So powerful and compelling were the visions that you devoted your life to the deity."),
                new ClassBackground("Sanctuary", "When you were young, you did a very wicked deed — or were accused of one — and fled to the only place that could shelter you from the law. You found sanctuary among the worshipers of a deity, and they took you in and protected you.In time, you joined the faithful to serve their cause in the world, though the shadow of your past sin still lurks beyond the church’s walls."),
                new ClassBackground("Taken in by the Church", "You spent your youth in a church or monastery serving as an acolyte or doing menial work on the grounds, either taken in as an orphan, sent there by your equally devout parents, or by taking on the faith of your own volition. The traditions and rituals of the religion served as your way of life throughout your adolescence, and you left that pious community with the skills to champion your faith in the world."),
            };
        }

        public List<ClassBackground> DruidBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Lost in the Wild", "You got lost in the wilderness and were forced to survive on your own. You may have wandered desert dunes, thick forest, or high mountains — or perhaps you were shipwrecked on a desert island. Young and vulnerable, you feared the natural dangers of the world at first, but acclimated to the natural way of life as you learned to tap into the primal power of the world."),
                new ClassBackground("Fey Meeting", "Walking in the woods, you met a fey creature, such as a brownie, elf, nymph, gnome, sprite, or treant. This magical being taught you how to tend the natural world in the gentle manner of the fey."),
                new ClassBackground("Spirit of Nature", "Through a ritual, vision, or dream, you communed with a primordial spirit of nature. In the form of a majestic beast, this spirit charged you with preserving the natural world from those who would destroy it. You are instilled with the spirit of this creature—a small fragment of its power grows in you as you mature."),
                new ClassBackground("Tree Tender", "You learned to care for plants in your youth by tending a small garden, orchard, grove, or field. These plants flourished like no others. You’ve always understood plants better than people."),
                new ClassBackground("Druid Circle", "You discovered, or were initiated into, a circle of druids that protects an expanse of wilderness. The druids taught you of their duty to nature and the powers that the natural world granted them. Soon you learned enough to join the circle as an initiate."),
                new ClassBackground("Civilized Outcast", "For a time, you lived in an urban environment. But you soon discovered that social communities, bureaucracies, and laws made you feel constrained and unnatural. You left civilization and retreated into the wild at the first opportunity. You still retain the lessons, habits, and refinements of civilized behavior, but your heart belongs to nature."),
                new ClassBackground("Savage", "You spent your formative years among a tribe or village far from civilization. The elders chose you as successor and taught you the lore of the elements and the animals."),
                new ClassBackground("Raised by Beasts", "You were reared in part by wild animals. Most of what you know you learned by observing these beasts, their natural instincts being unburdened by artifice or manipulation. Even though you possess a humanoid body, the beasts recognize you as one of their own."),
                new ClassBackground("Avatar", "Once you were an ordinary youth. But when the natural world needed saving, the land chose you as its champion, lending you as much power as you were able to control. You might not understand the reasons for your power, but you are one with nature and your will is the will of the world."),
                new ClassBackground("Beastlord", "Natural birds and beasts have always obeyed you. From your earliest years, you’ve possessed a gentleness or a power that allows you to communicate with animals as though you shared a common language. Perhaps you have fey blood or traces of lycanthrope ancestry."),
            };
        }

        public List<ClassBackground> FighterBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Adventure", "Since you can remember, you sought to become a great warrior. Inspired by legends of the past or personal heroes of your civilization, you longed to wield steel and carve your way in the world."),
                new ClassBackground("Conscripted", "You didn’t choose the military life so much as you were drafted into it. You have a non-military background and skill set. Who knows what course your life might have taken had you not been forced to take up arms?"),
                new ClassBackground("Duty", "You took up the sword because no one else would.When a great danger threatened your home, you stepped forth to meet the challenge, though you were only a youth with just the strength of your arm and steadfastness of your courage to see you through."),
                new ClassBackground("Gladiator", "As an adolescent, you learned to fight and kill because your master made you, and if you had not learned, you would be dead. Killing was a way of life — a means of survival. At first you did it because you had to, but that soon changed when you heard the chorus of the crowd."),
                new ClassBackground("Joined the Watch", "Your village, town, city, or tribe needed new recruits for the volunteer watch patrol, and you joined up—whether for money, duty, peace, or power.This rudimentary training gave you an understanding of civilized justice and showed you how to wield a weapon with skill."),
                new ClassBackground("Knighted", "Your military path began when you were knighted or made a squire to a knight. Your family’s status could have influenced this event, or you might be a simple commoner rewarded with a title for a rare feat of courage."),
                new ClassBackground("Mercenary", "Everyone needs to earn a living, and in your youth you were fast, strong, or tough enough to fight for pay.There are good causes and bad causes, but at the end of the day, it all comes down to money.Sometimes you got easy jobs, like guarding merchant caravans; other times the jobs are rough, like fighting in a rebel lord’s private army."),
                new ClassBackground("On the Street", "You spent adolescence in a seedy part of town. You learned to fight dirty and fight mean. Turns out you were good at it. Your skills drew the interest of gang and guild leaders, tavern keepers, and anyone else who needed hired muscle."),
                new ClassBackground("Schooled", "You learned to fight in a structured environment where you were exposed to a variety of weapons, armor, strategies, and tactics. You learned to fight as part of a unit, how to follow orders and how to command a squad."),
                new ClassBackground("Survival", "You spent some part of your life in the wild—in places that abide by the laws of nature rather than those of civilization. You survived by being stronger, faster, and more cunning than the predators. That meant you fought not for coin, honor, or principle, but for your very life."),
            };
        }

        public List<ClassBackground> GunslingerBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Any Fool Can Swing a Sword", "Sometime during your youth, you came to the conclusion that most melee and ranged weapons are crude and primitive compared to firearms. It puzzles you that anyone with martial aptitude deigns to devote their skill to anything other than firearms. You disregard such “lesser” weapons and prefer the feel of your trusty firearm over any other tool of war."),
                new ClassBackground("Bucking Tradition", "You come from a proud tradition of ancient arms and august codes of conduct like those followed by paladins, cavaliers, and samurai. Instead of following in the vaunted steps of your predecessors, though, you chose to learn the art of firearms to the shock and perhaps even anger of your family and peers. Your break with tradition fostered in you a nearly insurmountable will that fuels your identity as a gunslinger."),
                new ClassBackground("Custodian of the Future", "Firearms are not just an effective implement for killing or a curious mechanical trinket; they are the next step in the technological development of your people. Your passion for the workings of your weapons has you constantly assembling and dismantling firearms to truly understand their mechanics. This ongoing dedication improves your ability to repair firearms and make them deadlier while in your skilled hands."),
                new ClassBackground("Defining Moment", "Guns are inexorably linked to a moment where your life dramatically changed. Perhaps you were so sickly as a child that you couldn’t turn a crossbow’s winch or bend a bow, but firearms showed you that you could still hunt and fight. Perhaps you picked up a firearm in a desperate moment to help a wounded gunslinger and knew that you had just taken your first step along the same path. A firearm at your side instills in you a sense of purpose and destiny that no one can take away."),
                new ClassBackground("Look at What I Can Do", "The lure of something new and showy drove you to first pick up a gun. Although several near mishaps taught you to respect the volatile weapon and the powder that powers it, you still enjoy doing trick shots and getting the oohs and aahs of a crowd."),
                new ClassBackground("Mechanical Savant", "For you, the lure of firearms is not the effect they produce, but the science and mechanical process behind the effect. Your endless tinkering and perfectionism have made your own gun easier to upgrade."),
                new ClassBackground("Black Powder Presence", "You grew up belittled and even beaten for not being the biggest or the strongest of your compatriots, family, or race. With no burgeoning aptitude for magic, you looked for some other way to exceed those who found superiority in brute strength — and you found it in gunslinging."),
                new ClassBackground("Sacred Charge", "Your gunslinger training is more than just martial skill—it’s a calling. Perhaps you are part of an elite group of guards serving and defending a temple or faith. Conversely, you might come from a land where firearms represent the pinnacle of your society’s advancement or are the last vestige of those who came before. Your sense of higher purpose allows you to fight on and keep firing when winning seems impossible."),
                new ClassBackground("Shock and Awe", "The sound and fury of gunfire is as potent a weapon as the pellets and bullets your weapon discharges. You live for the reflexive wince that others make when they jump at the sound of a firearm, and laugh heartily at the amazement you inspire in others with your cacophonous black-powder weapons."),
                new ClassBackground("Some Things Are Stronger Than Magic", "You grew up either oppressed by magic cruelly wielded or loathing the elitism of those who possessed such arcane or divine power. Searching for something nonmagical that relies on skill and practice led you to the study and wielding of firearms.You relish trumping pompous spellcasters with a quick draw and a keen eye."),
            };
        }

        public List<ClassBackground> InquisitorBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Bureaucracy's Bane", "You chose the inquisitor’s path because you have no taste for the petty rules and regulations that mire the leaders of your faith in inaction and inefficacy.You know that you are an instrument of your deity and that your directives do not require intercession by the less motivated."),
                new ClassBackground("Chaplain", "You learned long ago that in the heat of battle and under the pall of war, even the most devout can waiver in faith. You subsequently dedicated yourself to stewarding the faith of soldiers and allies in times of great conflict."),
                new ClassBackground("Exemplar", "You found early on that you lacked the logic or the vocabulary to communicate the virtues of faith — more precisely, your faith — to others. You decided that the best way to foster respect and appreciation for your god was not with words, but with action."),
                new ClassBackground("Failed Cleric", "Your original training in divine magic was as a cleric, but your faith eventually distilled into you the ability to hear lies and see weaknesses in the 'unfaithful.'"),
                new ClassBackground("Faith-Bringer", "You know that in order to bring the light of your deity to others, you must traverse hostile territories and face even more hostile inhabitants."),
                new ClassBackground("False Witness", "You’ve seen innocent people suffer due to another’s lies. While these injustices made you feel powerless, they’ve also kindled a desire in you to punish those who regard truth so cheaply."),
                new ClassBackground("Few Left to Safeguard the Faith", "You are the vanguard of your faith. Perhaps you are a pilgrim for a good deity in an unholy land, or the secret enforcer of a sect that operates in the shadows of the world.You are accustomed to working alone and with little guidance from the superiors of your church, trusting your own moral judgment to act on behalf of your god.This certainty acts as a defense against the magic of other, “lesser” deities."),
                new ClassBackground("Temple Detective", "Your ability to sniff out falsehood and see weakness in others made you uniquely suited to guard the religious houses of your order."),
                new ClassBackground("The Path of Righteous Rage", "Your faith does not manifest in calm prayer or serene meditation. You achieve the transcendent feeling of the divine when you are in the throes of battle for your deity."),
                new ClassBackground("Zealot", "Your devotion is fanatical and your powers are clearly proof of your connection with the divine. Although you know that other gods bestow similar powers upon their own disciples, you either revile or pity those of “lesser” faiths."),
            };
        }

        public List<ClassBackground> MagusBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("A Mage without Magic", "Early in your arcane training, you were exposed to antimagic. The powerlessness you felt from all of your magic being stripped away left you feeling desperate and helpless. You vowed to never be that helpless child again, to be strong in such moments, putting you on the path of the magus."),
                new ClassBackground("Conflicting Legacy", "You were born to a family or clan with two great pedigrees: one of magic and one of battle. Unable to choose either path for fear of alienating a mentor or parent, you sought to master both.Your dedication to the blending of martial and magical has been so intense that your martial prowess feeds your arcane power."),
                new ClassBackground("Ready for Anything", "For you, the path of the magus is not about the fluid blend of disparate fields of study or conquering an insurmountable challenge, but the art of preparation for any obstacle that comes your way.A dedicated and logical person, you hone the magus affinity for operating all manner of magical devices from blind luck to a refined procedure."),
                new ClassBackground("Lost Teacher", "Your magus training was interrupted when you lost your teacher through the displacement of your family, lack of funds to continue schooling, or the teacher’s unexpected death.Despite this hardship, the time you spent with your mentor had already sown the seeds of your training and you’ve been able to continue on your own in the time since—ceaselessly seeking, reading, and learning from any magical text you can find."),
                new ClassBackground("Promise Keeper", "Your dreams of becoming a wizard were cut short by unfortunate circumstances, such as the death of your family or clan’s matriarch or patriarch, hostile invading forces, conscription in the army, and so on. This forced you to become a protector and stunted the growth of your studies. Though you have successfully blended the two disciplines, you still long for the unfulfilled potential of your career as a wizard."),
                new ClassBackground("Shameful Secret", "You come from either a proud military and martial background or a legacy of skilled wizards. When you developed an aptitude for two different powers viewed as incompatible by your family or teachers, it drove you to hide half of your abilities and to pretend full-blown competency with the other. Some of the tricks you used to perpetrate this deception have stayed with you to this day."),
                new ClassBackground("Spell Backfire", "At some point during your magical training, you attempted to cast a spell and failed. But rather than being wasted, the arcane energy reabsorbed itself into your body, waiting to be reused in some other way. When the arcane energy exploded outward through your staff or some other instrument you wielded, you received your first glimpse of the ways that magic could be repurposed — a versatility you retain today."),
                new ClassBackground("Spell's Edge", "The first time you held a magic weapon and felt the thrum of arcane energy within, you knew that magic and melee were meant to be joined. Since that moment, magic weaponry has become symbolic of the most potent syntheses of your magus training, and your ability to create magical weapons and imbue mundane arms with magic still resonates with this focus."),
                new ClassBackground("Vindication", "You spent your formative years trying to convince combat instructors of the virtues of magic and arcane mentors of the importance of strength in arms, only to be mocked and exiled from both disciplines. Since then, you’ve wandered from master to master, honing your knowledge of both fields of study to show them all that not only have you achieved power, but you’ve also eclipsed all those who shunned you."),
                new ClassBackground("What If", "You don’t know the meaning of impossible. Everyone around you thinks you have your head stuck in the clouds, but you continually strive to achieve things that have never been accomplished before — perhaps things that have never even been dreamed of. Bucking convention has brought numerous failures, but you’ve learned from your mistakes and are able to snatch victory over seemingly impossible odds."),
            };
        }

        public List<ClassBackground> MonkBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Bellicose Historian", "What started as a scholar’s curiosity in exotic fighting styles bloomed into a fanatical desire not just to learn about martial arts, but to master them."),
                new ClassBackground("Classically Schooled", "Training from dawn to dusk to hone every inch of your body into a fighting instrument, you studied with scores of other students in an academy or school dedicated to one specific martial art."),
                new ClassBackground("Elite Fighting Force", "You learned your fighting skills as one of a highly trained group dedicated to a special purpose, such as guarding a temple or protecting a noble. Your training emphasized unobtrusive teamwork and unquestioned dedication to some higher purpose."),
                new ClassBackground("Tournament Champion", "A shining example of your style or order, you’ve honed martial prowess through spirited and exciting competition."),
                new ClassBackground("Lineage Holder", "You are the senior or sole student of a great master. You rose to prominence early and received secret training in an art that is rare and exotic. Having achieved a strong foundation in the physical and metaphysical elements of this martial art, you’ve been designated the lore keeper for its history and traditions, and must now find new student or students to train."),
                new ClassBackground("Nature's Disciple", "Just as many great masters learned and crafted styles from the beauty and majesty of nature, your fighting style comes from time spent in the wild rather than from formal training. You have seen firsthand how the mantis hunts, how the tiger swipes, and how the crane beats its wings. Your observance of the natural world gave you the ability to extrapolate combat forms without traditional training."),
                new ClassBackground("Secret Student", "Your teacher and fellow students grew up as part of a conquered people, forbidden to train at war and forced to conceal the fighting style as seemingly harmless dances and your weapons as mundane tools… until the day you all you could rise up against tyranny."),
                new ClassBackground("Spirit Teacher", "Your martial training is both physical and metaphysical in nature, allowing you to unlock a higher state of consciousness that allows you to draw on the wisdom and power of long-dead masters."),
                new ClassBackground("Unsuspecting Master", "You were trained in martial arts through unorthodox methods such as seemingly menial tasks or training through conditioning exercises that promised the smallest scrap of food as a reward. Your nontraditional training makes you resourceful and clever."),
                new ClassBackground("Wandering Savant", "Although you’ve received some formal training in exotic combat, you decided to put your skills to the test and further your learning by wandering the wide world."),
            };
        }

        public List<ClassBackground> OracleBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Battle", "In your early years, a battle broke out near your home and you were embroiled in the fighting. At the end of the battle, you were the only one left standing, with scores of slain foes strewn at your feet."),
                new ClassBackground("Bones", "In your formative years, you were entombed or buried alive in a graveyard. For days, you lay within the grave until your terror strangely turned to comfort. Since your return, you’ve been a different person: part mortal and part ghost, in possession of the powers of the dead."),
                new ClassBackground("Flame", "A great fire consumed you and laid waste to the environment around you. It might have devoured your family, friends, or an entire settlement, but you survived unburned as if the fire did not dare to touch you.Since that day, you’ve tamed fire as though it were a savage animal bent to your will."),
                new ClassBackground("Heavens", "The night sky’s mysteries have always enthralled you. But one night, while you gazed upon the stars, the perfect order of the universe revealed itself and you nearly went mad from the revelation.Since that night, you’ve possessed strange powers over the heavens."),
                new ClassBackground("Life", "A terrible plague afflicted your homeland, killing thousands. You caught the disease, but instead of dying from it, you flourished. As you grew healthier, so did everyone you came into contact with."),
                new ClassBackground("Lore", "You were able to speak before any other child your age. Rather than stumble through the rudimentary syllables of language, you spoke in full sentences, reciting the greatest literature of many languages in story, song, and poem. Sometimes you spoke of events that had not yet come to pass, and the wise came to seek your counsel. Your gift came at a cost, however — though your knowledge is vast, your body and mind carry a curse."),
                new ClassBackground("Nature", "You became separated from your family and lost in the untamed wilderness for many days, months, or years.The wilderness took its toll, but when you finally emerged from the wild, you were its master."),
                new ClassBackground("Stone", "You were buried beneath the earth, possibly after an avalanche or earthquake. For 3 days the earth covered you, until at the end of the third day you emerged from the mountain unharmed but not unchanged."),
                new ClassBackground("Waves", "You were swept beneath the surface of the water once. You should have drowned, but instead you washed up on shore after a long interval. You emerged from the depths afflicted with a strange condition but otherwise unharmed."),
                new ClassBackground("Wind", "In your early years, you were caught in a powerful storm that ravaged the countryside, destroying everything in its path. Bolts of lightning struck your body and thunder deafened your ears, but when you came to the storm’s tranquil center, the tempest ceased. Since then you’ve had power over storms, though you still bear the mark of the great storm you endured."),
            };
        }

        public List<ClassBackground> PaladinBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Divine Calling", "An otherworldly agent of law and good — such as an angel, empyreal lord, or perhaps some other celestial envoy of the gods — tasked you to be a divine champion. You accepted the calling (maybe grudgingly) because ultimately you realize that the laws of destiny and one’s divine calling cannot be denied. In return, that celestial agent watches over you and makes sure you can fully realize your destiny and meet the course that has been set for you by a higher power."),
                new ClassBackground("Dread Penance", "You, or perhaps your family, owe a debt for some past wrongdoing or vice. Maybe you made deals with some unscrupulous loan sharks during a gambling binge or your not-so-distant ancestors were responsible for the persecution of a marginalized group of people. Whatever the offense, your past action hangs over your head and fills you with guilt. You’ve taken a solemn oath to make good on this past misdeed.Only then will you feel like your life is truly worthwhile."),
                new ClassBackground("Holy Epiphany", "Your faith and purpose came in a brilliant flash of insight. Maybe you suddenly realized that evil can be stopped only with vigilance and deliberate action, or maybe an epiphany showed you that the innocent need protection from corrupt forces for good to flourish in the world.Whatever the nature of your epiphany, it guides your actions and gives you insights others lack."),
                new ClassBackground("Zealous Devotion", "Maybe your faith was not popular among those around you during your youth. Maybe you have strange or controversial views regarding your religion, and the other members of your congregation find your practices bizarre or insulting. Whatever the case, your faith is constantly being questioned regardless of your obviously pious nature, and such persecution only serves to embolden your zeal."),
                new ClassBackground("Moral Debt", "The world and all things material are intrinsically corrupt. All creatures are born with a moral debt, and only by fighting evil, upholding law, and championing the common good can one be truly free of that corruption. You work every day to pay off this debt and move those around you to do the same."),
                new ClassBackground("Mark of Faith", "You were born with the mark of your faith. Maybe at some point you rebelled against such branding, or it could be you’ve always accepted the mark as an indicator of your destiny. In either case, it was a harbinger of the paladin path."),
                new ClassBackground("Righteous Mentor", "A paladin of note and great honor took you under her wing and taught you many things. She taught you how to adhere to your oath with grace and dignity, and how the simple act of doing so was enough to earn the respect and devotions of others."),
                new ClassBackground("Warrior of Truth", "Early in your life, you learned that the philosophies of law and good not only create the best society but also reveal truths that would otherwise remain obscured. You are rarely clouded by pure dogma; instead you’re unafraid to question and create your own path toward truth, justice, and righteousness."),
                new ClassBackground("Knight-Errant", "You know that evil stalks the world, and only one who is dedicated to the spread of good can stop these vile forces. To make sure fiends and wrongdoers do not go unpunished, you adopted the code of the paladin in order to travel the land and eradicate the wicked.Your goal is the relentless pursuit to seek out evil and put it down."),
                new ClassBackground("Terrible Secret", "You know a terrible secret about an ancient evil that threatens your homeland or perhaps even the entire world. You have sworn to keep this secret quiet lest it gain power in the retelling, but you also must work to thwart the evil whenever possible. This at times contradictory path has led you many places in your travels, and the knowledge you have gleaned from your adventures continues to serve you well in your fight against the wicked."),
            };
        }

        public List<ClassBackground> RangerBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("An Eye for an Eye", "The choice of your favored enemy was nothing more than simple vengeance. Perhaps you lost a loved one, family, or even a whole community to the vicious rampaging of a ferocious beast, or saw your entire homeland swallowed up by monstrous hordes. No matter the reason, your drive to hunt down and destroy creatures of their kind won’t be sated so long as even one lives."),
                new ClassBackground("Ancient Hatred", "The history of your people is a saga of struggle against another race. Though common among elves and orcs or dwarves and giants, many different races can have such longstanding animosity. Your choice of a favored enemy was a simple outgrowth of this racial antipathy."),
                new ClassBackground("Big Game Hunter", "Whether you sought out the thrill of hunting large prey or merely grew up in the shadows of creatures large enough to crush an entire village with a careless step, you have learned how to be quick and to size up weaknesses in those behemoths who seem to have none."),
                new ClassBackground("Blood Cleansing", "Either you have forsaken your kinsfolk or they have forsaken you. Maybe you grew up among a wicked or corrupt people who you needed to escape, or maybe they exiled you for being different. Whatever the case, your own kind are now your favored enemy, much to your continued chagrin or morbid amusement."),
                new ClassBackground("Bounty Hunter", "You have always been good at finding and extracting people from their hidey-holes. Most likely you hunt humanoids of either your own subtype or of one common to your region."),
                new ClassBackground("Detached Observer", "You set yourself apart with a pall of cold logic that allows you to see weaknesses in members of your own race that you strive not to succumb to yourself. Most likely, you pick your own race as your dominant favored enemy, and you excel as a spy or assassin paid to capture enemies of your organization."),
                new ClassBackground("Divine Purpose", "Not all those who hear the voices of the gods can distill that echo into magical power like clerics or oracles. These whispers of belief encouraged you to track and hunt those creatures who pose the greatest threat to your faith. Perhaps you’re a good ranger who hunts the undead or devotes effort to slaying fiends, or you could choose to target good fey and celestials, emboldened by divine invective."),
                new ClassBackground("Nightmare Slayer", "From an early age, you stood up against some of the most terrifying creatures imaginable, facing off against creatures most mortals only dream of in their wildest nightmares. Possibly hailing from lands besieged by dragons or plagued by the living dead, you are not only resistent to the fear such creatures normally engender, but you live to show your enemies the face of the unafraid."),
                new ClassBackground("Opportunist", "You are an expert in creatures both common and exotic, particularly in terms of what valuable items you can harvest from their remains. The natural world exists for the benefit of those who know what to take, and you have learned how to scavenge pelts, toxins, and even rare spell components from your defeated foes.You might pick animals, magical beasts, or dragons as your dominant favored enemy — or humanoids if you’re a particularly grisly trophy collector."),
                new ClassBackground("Survivalist", "You were orphaned at a young age and left to fend for yourself in the wilds, or simply lived a life at the edge of society that required a constant scrabble for basic existence. You probably have animals or magical beasts (the edible ones) as your dominant favored enemy, and are adept at lying in wait and springing into action."),
            };
        }

        public List<ClassBackground> RogueBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Gang War", "Growing up in the backstreets of an urban jungle, you were forced to choose between surviving as a predator or suffering as prey. You affiliated with a guild, gang, or group of thieves and thugs, carrying out illicit missions to further their interests and sabotage those of rival gangs."),
                new ClassBackground("Greed", "No matter how much or little you had growing up, it was never enough. You discovered a talent for lifting items and coin purses from others’ belts.The world always provided for you, and when you saw something you wanted, you learned to take it."),
                new ClassBackground("Poverty", "In your youth, you rarely had enough food to keep from starving. Poverty and hunger forced you to steal to survive, or to help your loved ones survive."),
                new ClassBackground("Spy", "You’ve always had an innocent expression and a silver tongue, so naturally you were recruited as a spy during your childhood. You could have come from any social class; you might have gathered information as an urchin on the streets or acted as servant to one lord while you reported to another."),
                new ClassBackground("The Kill", "You killed someone when you were relatively young. You might have done it in selfdefense, in anger, or as part of an initiation ritual. And it was easier than you suspected. Afterward, some individuals or groups started paying you to kill for them, and you made a lucrative career of assassination."),
                new ClassBackground("The Trained", "Your early talent for feats of agility and acrobatics garnered you an experienced mentor. Impressed by your natural ability, this mentor taught you how to fight, dodge, and throw. He may have been a master thief, circus performer, fencing master, or swashbuckling pirate."),
                new ClassBackground("Outlawed", "For reasons just or unjust, you became a fugitive at an early age. You have lived outside the light of society for some time, risking capture or punishment whenever you need to break the law again."),
                new ClassBackground("Thrill Seeker", "As an adolescent, you and your friends took turns daring one another to take risks, each new challenge inspiring greater excitement. Since then, you’ve become an adrenaline junkie, performing dangerous tasks in order to chase that high."),
                new ClassBackground("Henchman", "You’ve always worked for someone else.You do what you are told and in return you are appreciated by the boss, rewarded, and paid."),
                new ClassBackground("Scout", "Your natural ability turned into employment in an elite squad of stealthy infiltrators. You penetrate enemy lines, gather information, deliver coded messages, and sabotage enemy supplies. You likely work for a private individual or military order."),
            };
        }

        public List<ClassBackground> SorcererBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Awakened Moment", "At some point, the dormant power within you awakened with a fright. It might have been the first time you came close to a dragon, celestial, or genie. Or the moment couldhave come at the grave of a great ancestor or in a lush and verdant glen. What slumbered in your blood has never quieted, and you frequently draw upon the inspiration of your awakening."),
                new ClassBackground("Dreams of Something Different", "The first hints of your exceptional nature came to you as fragments of remembered dreams or split-second visions. As these episodes increased in both frequency and clarity, they unlocked a power in your blood you didn’t know you had."),
                new ClassBackground("Failed Wizard", "Although your arcane aptitude was evident at an early age, you were pushed toward wizardry as the conduit for your magic. While you never mastered magic in this fashion, your time spent studying arcane tomes gave you obscure but often pertinent knowledge."),
                new ClassBackground("One of a Kind", "You know that sorcerous power comes from the blood, but as far as you know, none of your ancestors possessed your gift. You keep searching for the reason for your magical powers, which has led you to greater proficiency with divinations and a keen interest in the workings of your bloodline."),
                new ClassBackground("Outcast", "Driven away by your family and people, your arcane gifts have always inspired both fear and revulsion. You’ve become adept at spotting hostility in others who would despise you for your power."),
                new ClassBackground("Proud Heritage", "You hail from a long line of prominent sorcerers with even more prominent ancestral features. Your acceptance of your bloodline brings with it a pride and imposing mien that becomes amplified among others."),
                new ClassBackground("Shameful Heritage", "The obvious hints of your heritage were a source of shame to your family. No matter the manifestation of your differences, being a pariah taught you to practice your arts in secret."),
                new ClassBackground("Too Lucky", "You’ve always had a knack for getting out of trouble. This sense of preternatural good fortune led to your inquiries into magic and the discovery of your own sorcerous powers."),
                new ClassBackground("Unharmed", "At some point in your early life, you were exposed to something dangerous like a fall into stormy waters or a spell cast your way. But instead of dying, you survived entirely unscathed. This experience either first hinted at or confirmed that you were different, marking the first step on your path to sorcery."),
                new ClassBackground("Wild Talent", "The magic in your blood was always as uncontrollable as it has powerful. You were forced to learn control at an early age, either out of fear that your powers might hurt someone or out of remorse once they had. This relentless vigilance and self-control gave you tremendous focus and arm you with strategic methods to redirect those wild energies coursing through you."),
            };
        }

        public List<ClassBackground> SummonerBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Abandoned", "At some point early on, you were abandoned. This sense of loss always made you feel as though something were missing. The discovery of your eidolon and your subsequent mutual bond fostered in you the sense of companionship you’ve always longed for."),
                new ClassBackground("Caretaker", "You met your eidolon or another outsider in a moment of danger. Wounded or lost, the creature crashed between worlds and ended up at your feet. In helping this panicked, otherworldly creature, you felt a link to it. You can still draw on the inspiration from that moment when dealing with others, outsider or not."),
                new ClassBackground("Forced to Confront Your Own Limits", "The bond with your eidolon first manifested when you saw someone in danger and were unable to help. Your feeling of desperation and frustration at the limits of your own form attracted your eidolon — whether or not it was able to help you in that moment. This need to exceed your own limitations continues to manifest in the evolution of your eidolon."),
                new ClassBackground("Imaginary Friends", "As a child, you created imaginary playmates that you felt truly spoke to and heard you. These whispers were actually the wandering thoughts of outsiders trying to make contact, knowing that someday you would have an affinity with their kind. By the time you learned to summon your eidolon and other outsiders, these whispered fragments had turned themselves into an understanding of the language of outsiders."),
                new ClassBackground("Monophobic", "You were always terrified of being alone when you were younger, so you surrounded yourself with others. But it was establishing this link to your eidolon that ultimately allowed you to overcome this debilitating fear. Now, even when your eidolon is not with you, you know it’s never far away; conversely, when you have your true friend and companion with you, you are far better for it."),
                new ClassBackground("Outsider's Lineage", "You have the blood of outsiders in your veins. This lineage either laid dormant until your powers manifested or was a storied part of your family heritage. Regardless, your connection to the planes has always been potent. No matter what other subjects you studied, your understanding of planar matters has always seemed instinctive or innate rather than the product of memorization and study."),
                new ClassBackground("Pick On Someone Your Own Size", "When you were young, you or others you cared for were bullied by agents of an oppressive power.At some point, you stood up against one or many of the tyrants, feeling that somehow you were bigger, stronger and more resilient than you actually were.You later realized that this support was the first trace of your eidolon trying to make contact with you. You can still draw on that power today, making your aura strong and your presence powerful."),
                new ClassBackground("Raising Gone Wrong", "You lost someone important to you. Through means, luck, or simple pity, you had the chance to raise that person from the dead, but something went wrong with the spell and the raising did not occur… at least not as planned. Your lost friend or kin’s soul bonded with a powerful outsider on the other side of the veil and returned to you as your eidolon. Possessed of some of the memories and experiences of the life you spent together, your companion feels a stronger devotion than even most others of its kind."),
                new ClassBackground("Saved by Another", "Someone or something saved you from great danger. It might have been a family member who saved you from a precipitous fall or adventurers who saved you from a marauding monster. Your sense of gratitude fostered a strong sense of protectiveness, particularly when defending your allies or your eidolon."),
                new ClassBackground("Stranger in Your Own Skin", "You have felt awkward and uncomfortable your entire life, as if you were born into a body that wasn’t truly yours.Your quest to become what you’ve always felt you should be led you to your eidolon, in which you found what you see as your own idealized form.The link that you and your eidolon share allows you to escape some of the inherent limits of your form from time to time."),
            };
        }

        public List<ClassBackground> WitchBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Apprenticed", "Your development was guided by a mortal or magical creature, such as a wisewoman, hag, dryad, elf, or pixie, who instructed you in the arts of spellcasting, potions, charms, and hexes."),
                new ClassBackground("Desperate Accident", "You lived an ordinary life until one day catastrophe struck and you called out desperately to any power that would come to your aid. The entity that gave you this power might be benevolent or sinister in nature, but ever since you called it, the being remains close to you."),
                new ClassBackground("Forbidden Lore", "In your youth, there was something you fervently desired—perhaps love, wealth, or revenge. But no matter how hard you tried, you couldn’t obtain that which you coveted. Only when you turned your eye to ancient tomes and ruins and experimented with strange powers beyond your comprehension were you able to get what you wanted."),
                new ClassBackground("Found Familiar", "When you were young, you happened upon a strange animal with whom you forged an instant bond. It instructed you in casting spells and became your closest, most trusted companion."),
                new ClassBackground("Gifted", "You received your magical ability as a gift from a supernatural being, such as an angel, devil, god, ancient dragon, or powerful fey. This creature expects you to act on its behalf in exchange for the power it loaned you."),
                new ClassBackground("Inborn Power", "Many fey creatures are born with the innate ability to cast spells, and either because of having fey blood in your lineage or being born near fey lands you too were gifted this talent."),
                new ClassBackground("Initiated", "When you came of age, a coven of witches initiated you into their circle because you showed great promise. After your initiation ritual, you changed on a fundamental level."),
                new ClassBackground("Invocation", "When you reached adolescence, you wanted power and you wanted it immediately. You didn’t have the patience or tolerance to endure endless years of boring theory and formal magical training, so you offered up your body and soul in an invocation to an entity that would grant your desire."),
                new ClassBackground("Possessed", "For reasons you may never understand, an otherworldly entity took possession of you in your formative years. Since then, your mortal body has been the vessel for this mysterious power."),
                new ClassBackground("Unknown", "The circumstances by which you gained your powers are confusing, even to you. You may have received them when you stepped into a enchanted land or touched a strange artifact, or perhaps you simply awoke one day with them. You strive to find the meaning of your powers, as they drive your life in unforeseen directions."),
            };
        }

        public List<ClassBackground> WizardBackgrounds()
        {
            return new List<ClassBackground>
            {
                new ClassBackground("Brains over Brawn", "You were bullied or excluded throughout your life because you lacked physical power and fighting prowess. To compensate, you turned to transmutation magic. Your practice and perseverance has granted you skill with spells of that school."),
                new ClassBackground("Dangerous Intellect", "At a young age, those around you, whether family or friends, realized that your intellect was more than mere precociousness. As your sense of curiosity became dangerous, those responsible for you pushed you into studying magic in the hopes that you would find infinite puzzles to solve."),
                new ClassBackground("Fitting In", "You hail from a long line of sorcerers or from a community known for its natural affinity for magic.Your manifestation of wizardly talent, as opposed to blood-based sorcery, caused you to hide those talents at a young age, and then to disguise them as sorcery to the best of your ability later.You still retain some tricks from this early misdirection."),
                new ClassBackground("Gifted Pride", "Your affinity for magic has made you somewhat crass and arrogant, though some find your blunt disposition charming or worthy of respect. The air of superiority surrounding you is palpable and allows you to use you intellect to cow others at times when lesser individuals might barely get a word in."),
                new ClassBackground("Mortality's Mirror", "Your childhood innocence ended the moment you realized that someday you would die. This revelation may have come to you at the deathbed of a beloved relative, during a bloody siege against your homeland, or via some other eye-opening event. You have spent the rest of your life trying to master magic in order to change this most universal fate from stealing your last breaths away. You now have a keen eye for the magic of death and for discerning answers to ancient riddles."),
                new ClassBackground("Righting a Wrong", "In your youth, you witnessed an event that changed the fate of many or of a tragic few, such as a natural disaster(like a flood, hurricane, or fire) or simply a friend’s unfortunate accident during a childish game.You were burdened by the knowledge that magic — perhaps even a spell as simple as feather fall — could have changed the course of lives.You’ve dedicated yourself to magic in an effort to make sure that you are never subject to the capricious whims of fate again."),
                new ClassBackground("Storied Lineage", "Your family name is synonymous with wizardry of the highest caliber. Magic was your destined path before you were even born, and both your family and those who know of your lineage have supported this notion your entire life, granting you an unwavering confidence in your talents. While the pursuit of arcane mastery is never easy, you are driven to live up to the expectations set forth for you."),
                new ClassBackground("The Way Things Work", "Magic came alive the first time you held a magic item. The notion of extraordinary magic resting within something as seemingly ordinary as a ring, amulet, or stoppered vial changed the way you viewed the world, and ever since you’ve possessed a sense of curiosity and awe for all magic items."),
                new ClassBackground("Unpaid Debt", "Someone saved your life at great cost. Whether through healing magic or basic heroism, your savior gave her life that you might live. Striving to repay this debt has led you to study magic, the only thing capable of making enough of a difference in the world to make you feel that you have earned the gift given to you. This sense of purpose has engendered an unshakable resolve in you."),
                new ClassBackground("Unquenchable Hunger for Knowledge", "For most wizards, magic is an end to which all studies strive, but not for you.For you, magic is a means to an end—and that end is knowledge. Your desire to know all of the secrets of the world requires the ability to cross continents in a blink, ride the winds, breathe water like a fish, and survive any kind of trap.Your unquenching quest for knowledge has made you ever ready for danger."),
            };
        }
    }
}
